# As of Symfony 5.1, deprecations are logged in the dedicated "deprecation" channel when it exists
monolog:
  channels: [deprecation]
  handlers:
    deprecation:
      type: stream
      path: "%kernel.logs_dir%/%kernel.environment%.deprecations.log"
      # channels: [deprecation]
    deprecation_filter:
      type: filter
      handler: deprecation
      max_level: info
      channels: ["php"]
